// <auto-generated />
using System;
using AIMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AIMS.Migrations
{
    [DbContext(typeof(AimsDbContext))]
    partial class AimsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AIMS.Models.Assignment", b =>
                {
                    b.Property<int>("AssignmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentID"));

                    b.Property<int>("AssetKind")
                        .HasColumnType("int");

                    b.Property<int?>("AssetTag")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SoftwareID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UnassignedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("AssignmentID");

                    b.HasIndex("UserID");

                    b.HasIndex("AssetTag", "UnassignedAtUtc")
                        .IsUnique()
                        .HasFilter("[AssetTag] IS NOT NULL AND [UnassignedAtUtc] IS NULL");

                    b.HasIndex("SoftwareID", "UnassignedAtUtc")
                        .IsUnique()
                        .HasFilter("[SoftwareID] IS NOT NULL AND [UnassignedAtUtc] IS NULL");

                    b.ToTable("Assignments", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_Assignment_ExactlyOneAsset", "\n                    (\n                        ([AssetKind] = 1 AND [AssetTag] IS NOT NULL AND [SoftwareID] IS NULL)\n                        OR\n                        ([AssetKind] = 2 AND [SoftwareID] IS NOT NULL AND [AssetTag] IS NULL)\n                    )");
                        });
                });

            modelBuilder.Entity("AIMS.Models.AuditLog", b =>
                {
                    b.Property<int>("AuditLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditLogID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AssetKind")
                        .HasColumnType("int");

                    b.Property<int?>("AssetTag")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ExternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoftwareID")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("AuditLogID");

                    b.HasIndex("AssetTag");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("SoftwareID");

                    b.HasIndex("UserID");

                    b.ToTable("AuditLogs", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_AuditLog_ExactlyOneAsset", "\n                    (\n                        ([AssetKind] = 1 AND [AssetTag] IS NOT NULL AND [SoftwareID] IS NULL)\n                        OR\n                        ([AssetKind] = 2 AND [SoftwareID] IS NOT NULL AND [AssetTag] IS NULL)\n                    )");
                        });
                });

            modelBuilder.Entity("AIMS.Models.Feedback", b =>
                {
                    b.Property<int>("FeedbackID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubmittedByUserID")
                        .HasColumnType("int");

                    b.HasKey("FeedbackID");

                    b.HasIndex("SubmittedByUserID");

                    b.ToTable("FeedbackEntries", "dbo");
                });

            modelBuilder.Entity("AIMS.Models.Hardware", b =>
                {
                    b.Property<int>("HardwareID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HardwareID"));

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssetTag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("WarrantyExpiration")
                        .HasColumnType("date");

                    b.HasKey("HardwareID");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("HardwareAssets", "dbo");
                });

            modelBuilder.Entity("AIMS.Models.Report", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportID"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ExternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReportID");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Reports", "dbo");
                });

            modelBuilder.Entity("AIMS.Models.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleID");

                    b.ToTable("Roles", "dbo");
                });

            modelBuilder.Entity("AIMS.Models.Software", b =>
                {
                    b.Property<int>("SoftwareID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SoftwareID"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SoftwareCost")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateOnly?>("SoftwareLicenseExpiration")
                        .HasColumnType("date");

                    b.Property<string>("SoftwareLicenseKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SoftwareName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoftwareType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SoftwareUsageData")
                        .HasColumnType("bigint");

                    b.Property<string>("SoftwareVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SoftwareID");

                    b.HasIndex("SoftwareLicenseKey")
                        .IsUnique();

                    b.ToTable("SoftwareAssets", "dbo");
                });

            modelBuilder.Entity("AIMS.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GraphObjectID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<int?>("SupervisorID")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("RoleID");

                    b.HasIndex("SupervisorID");

                    b.ToTable("Users", "dbo");
                });

            modelBuilder.Entity("AIMS.Models.Assignment", b =>
                {
                    b.HasOne("AIMS.Models.Hardware", "Hardware")
                        .WithMany()
                        .HasForeignKey("AssetTag")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AIMS.Models.Software", "Software")
                        .WithMany()
                        .HasForeignKey("SoftwareID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AIMS.Models.User", "User")
                        .WithMany("Assignments")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hardware");

                    b.Navigation("Software");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AIMS.Models.AuditLog", b =>
                {
                    b.HasOne("AIMS.Models.Hardware", "HardwareAsset")
                        .WithMany()
                        .HasForeignKey("AssetTag")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AIMS.Models.Software", "SoftwareAsset")
                        .WithMany()
                        .HasForeignKey("SoftwareID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AIMS.Models.User", "User")
                        .WithMany("AuditActions")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HardwareAsset");

                    b.Navigation("SoftwareAsset");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AIMS.Models.Feedback", b =>
                {
                    b.HasOne("AIMS.Models.User", "SubmittedByUser")
                        .WithMany("FeedbackSubmissions")
                        .HasForeignKey("SubmittedByUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubmittedByUser");
                });

            modelBuilder.Entity("AIMS.Models.User", b =>
                {
                    b.HasOne("AIMS.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AIMS.Models.User", "Supervisor")
                        .WithMany("DirectReports")
                        .HasForeignKey("SupervisorID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Role");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("AIMS.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("AIMS.Models.User", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("AuditActions");

                    b.Navigation("DirectReports");

                    b.Navigation("FeedbackSubmissions");
                });
#pragma warning restore 612, 618
        }
    }
}
